import { Inter } from 'next/font/google'
import Header from '@/components/Header/Header'
import Footer from '@/components/Footer/Footer'

import 'bootstrap/dist/css/bootstrap.css';
import '/public/vendor/core/plugins/language/css/language-publice209.css?v=1.0.0'
import '/public/themes/stories/css/styledf8a.css?v=1.16.3'
import '/public/themes/stories/css/widgetsdf8a.css?v=1.16.3'
import '/public/themes/stories/css/responsivedf8a.css?v=1.16.3'
import '/public/themes/stories/css/customdf8a.css?v=1.16.3'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
